language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install cython
  - pip install -U -r requirements.txt pytest-mock .
# command to run tests
script:
  - pytest

cache: pip

jobs:
  include:
    - name: "dependencies"
      script:
        - pip check
    - name: "coverage"
      script:
        - pip install -U -r requirements-dev.txt .
        - coverage run --source "$(basename "$PWD")" setup.py test
        - coveralls
    - name: "linting"
      script:
        - pip install -r requirements-dev.txt
        - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

notifications:
  email: never
