language: python

python:
    - '3.6'

cache: pip

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt .

before_script:
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

script:
    - coverage run --source "$(basename "$PWD")" setup.py test

after_success:
    - coveralls
    - pip check

notifications:
    email: never
