language: python

python:
  - '3.6'
  - '3.7'

cache: pip

jobs:
  include:
    - stage: "Build"
      name: "dependencies"
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements.txt .
        - pip check
    - name: "test"
      script:
        - pip install --upgrade pip
        - pip install cython
        - pip install -U -r requirements.txt -r requirements-dev.txt .
        - pytest
    - name: "coverage"
      script:
        - pip install --upgrade pip
        - pip install cython
        - pip install -U -r requirements.txt -r requirements-dev.txt .
        - coverage run --source "$(basename "$PWD")" setup.py test
    - name: "code formatting"
      script:
        - pip install --upgrade pip
        - pip install -r requirements-dev.txt
        - black --check cg
    - name: "linting"
      script:
        - pip install --upgrade pip
        - pip install -r requirements-dev.txt
        - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

after_success: coveralls

notifications:
  email: never
