dist: xenial
language: python

python:
    - '3.6'
    - '3.7'

cache: pip

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt .
    - pip install -U git+https://github.com/Clinical-Genomics/trailblazer@MIP7.1-dev
    - pip check

script:
    - coverage run --source "$(basename "$PWD")" setup.py test
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

after_success: coveralls

notifications:
    email: never
