language: python

python:
    - '3.6'

install:
    - pip install cython
    - pip install -r requirements-dev.txt .
    - pip install -r requirements.txt .
    - pip install scout-browser

script:
    - coverage run --source "$(basename "$PWD")" setup.py test
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

after_success: coveralls

notifications:
    email: never
