language: python

python:
    - '3.6'

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt -e .
    - pip install nose pylint

script:
    - coverage run --source "$(basename "$PWD")" setup.py test
    - nosetests && pylint --errors-only cg

after_success: coveralls

notifications:
    email: never
