language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install pip==18.1
  - pip install cython
  - pip install -U -r requirements.txt pytest-mock .
# command to run tests
script:
  - pytest

cache: pip

jobs:
  include:
    - name: "dependencies"
    - name: "production dependencies"
      script:
        - pip check
    - name: "development dependencies"
        script:
          - pip install -U -r requirements.txt -r requirements-dev.txt .
          - pip check
    - name: "coverage"
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements-dev.txt .
        - coverage run --branch --omit="*.html" --source cg setup.py test
        - coveralls
    - name: "code formatting"
      script:
        - pip install --upgrade pip
        - pip install black
        - black --check cg tests
    - name: "linting"
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements-dev.txt
        - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

notifications:
  email: never
