language: python
sudo: false
python:
    - '3.6'

install:
    - pip install -q -r requirements.txt .

script:
    - coverage run --source cg setup.py test

after_success: coveralls

notifications:
    email: never

deploy:
    provider: pypi
    user: robinandeer
    password:
        secure: fQsE+5FUuXWuLMuGVirfSEz7WBc09gxDbEcPfIJFUQ2FzaGCQ+OGZpb6sbNCrazhqwnyyJ7b4ZD3bjJ++kWsmnpgvdUFZRDUUpcLuDtwzPSxHVx/1Zax4gMnny83Z1yF4O7m8bXt7HG1mPuKzPSHLOcTg3SxTQEgSi27dkeY4WE=
    on:
        tags: true
        distributions: sdist bdist_wheel
        repo: Clinical-Genomics/cg
