language: python

python:
    - '3.6'

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt -e .

script:
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint && coverage run --source "$(basename "$PWD")" setup.py test

after_success: coveralls

notifications:
    email: never
