language: python
sudo: false
python:
    - '3.6'

install:
    - pip install cython
    - pip install -r requirements.txt -r requirements-dev.txt -e .

script:
     - py.test -rxs tests/

notifications:
    email: never
