FROM registry.access.redhat.com/ubi8/ubi:latest

ENV PYTHON_VERSION=3.11

RUN yum -y update && \
    yum -y install gcc openssl-devel bzip2-devel libffi-devel zlib-devel make wget && \
    yum -y install gnupg2 pigz tar && \
    yum clean all


RUN mkdir -p /home/bin

# CG expects these binaries to be availbable in /home/bin
RUN ln -s /usr/bin/gpg /home/bin/gpg && \
    ln -s /usr/bin/pigz /home/bin/pigz && \
    ln -s /usr/bin/tar /home/bin/tar

RUN cd /usr/src && \
    wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz && \
    tar xzf Python-3.11.9.tgz && \
    cd Python-3.11.9 && \
    ./configure --enable-optimizations && \
    make altinstall

RUN rm -rf /usr/src/Python-3.11.9*

RUN ln -s /usr/local/bin/python3.11 /usr/bin/python3 && \
    ln -s /usr/local/bin/pip3.11 /usr/bin/pip3

RUN groupadd --system nonroot && \
    useradd --system --gid nonroot --create-home --no-log-init nonroot

WORKDIR /app

RUN python3.11 -m pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi

COPY . /app/

USER nonroot
