FROM python:3.11-slim-buster

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone -b master https://github.com/Clinical-Genomics/cg.git /app

RUN pip install --no-cache-dir .

ENTRYPOINT ["cg"]
