FROM docker.io/library/python:3.11-slim-bullseye

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /app

RUN git clone -b master https://github.com/Clinical-Genomics/cg.git /app
RUN pip install --no-cache-dir .
