from datetime import datetime
from typing import List

from cg.apps.sequencing_metrics_parser.models.bcl2fastq_metrics import (
    Bcl2FastqSampleLaneMetrics,
)
from cg.apps.sequencing_metrics_parser.parsers.bcl2fastq import parse_bcl2fastq_sequencing_metrics
from cg.apps.sequencing_metrics_parser.sequencing_metrics_calculator import (
    average_quality_score,
    q30_ratio,
)
from cg.store.models import SampleLaneSequencingMetrics


def get_sequencing_metrics_from_bcl2fastq(
    stats_json_path: str,
) -> List[SampleLaneSequencingMetrics]:
    """
    Parses the Bcl2fastq generated stats.json file and creates a list of SampleLaneSequencingMetrics objects,
    each representing a sample in a lane on the flow cell.

    Args:
        stats_json_path (str): The path to the JSON file generated by Bcl2fastq.

    Returns:
        List[SampleLaneSequencingMetrics]: A list of SampleLaneSequencingMetrics objects representing the sequencing
        metrics for each sample in each lane on the flow cell.
    """

    sample_lane_sequencing_metrics: List[SampleLaneSequencingMetrics] = []

    sample_and_lane_metrics: List[Bcl2FastqSampleLaneMetrics] = parse_bcl2fastq_sequencing_metrics(
        demultiplex_result_directory=stats_json_path
    )

    for raw_sample_metrics in sample_and_lane_metrics:
        pass


def create_sample_lane_sequencing_metrics(
    raw_sample_metrics: Bcl2FastqSampleLaneMetrics,
) -> SampleLaneSequencingMetrics:
    """
    Generates a SampleLaneSequencingMetrics object based on the provided conversion and demultiplexing results
    along with the raw sequencing metrics.

    Args:
        raw_sample_metrics: Bcl2FastqSampleLaneMetrics: The raw sequencing metrics for a sample in a lane.

    Returns:
        SampleLaneSequencingMetrics: A SampleLaneSequencingMetrics object that encapsulates the statistics for a sample
        in a lane on the flow cell.
    """

    sample_base_fraction_passing_q30: float = q30_ratio(
        q30_yield=raw_sample_metrics.sample_total_yield_q30_in_lane,
        total_yield=raw_sample_metrics.sample_total_yield_in_lane,
    )
    sample_base_mean_quality_score: float = average_quality_score(
        total_quality_score=raw_sample_metrics.sample_total_quality_score_in_lane,
        total_yield=raw_sample_metrics.sample_total_yield_in_lane,
    )

    return SampleLaneSequencingMetrics(
        flow_cell_name=raw_sample_metrics.flow_cell_name,
        flow_cell_lane_number=raw_sample_metrics.flow_cell_lane_number,
        sample_internal_id=raw_sample_metrics.sample_id,
        sample_total_reads_in_lane=raw_sample_metrics.sample_total_reads_in_lane,
        sample_base_fraction_passing_q30=sample_base_fraction_passing_q30,
        sample_base_mean_quality_score=sample_base_mean_quality_score,
        created_at=datetime.now(),
    )
