PROP2UDF = {
    'require_qcok': 'Process only if QC OK',
    'application': 'Sequencing Analysis',
    'priority': 'priority',
    'source': 'Source',
    'comment': 'Comment',
    'customer': 'customer',
    'family_name': 'familyID',
    'quantity': 'Quantity',
    'tumour': 'tumor',
    'pool': 'pool name',
    'index': 'Index type',
    'index_number': 'Index number',
    'concentration': 'Concentration (nM)',
    'volume': 'Volume (uL)',
    'well_position_rml': 'RML well position',
    'rml_plate_name': 'RML plate name',
    'sex': 'Gender',
    'target_reads': 'Reads missing (M)',
}
