PROP2UDF = {
    'application': 'Sequencing Analysis',
    'comment': 'Comment',
    'concentration': 'Concentration (nM)',
    'concentration_weight': 'Sample Conc.',
    'customer': 'customer',
    'data_analysis': 'Data Analysis',
    'elution_buffer': 'Sample Buffer',
    'extraction_method': 'Extraction method',
    'family_name': 'familyID',
    'index': 'Index type',
    'index_number': 'Index number',
    'organism': 'Strain',
    'organism_other': 'Other species',
    'pool': 'pool name',
    'priority': 'priority',
    'quantity': 'Quantity',
    'reference_genome': 'Reference Genome Microbial',
    'require_qcok': 'Process only if QC OK',
    'rml_plate_name': 'RML plate name',
    'sex': 'Gender',
    'source': 'Source',
    'target_reads': 'Reads missing (M)',
    'tumour': 'tumor',
    'tumour_purity': 'tumour purity',
    'volume': 'Volume (uL)',
    'well_position_rml': 'RML well position',
    'verified_organism': 'Verified organism',
}
