"""add application table to admin

Revision ID: 3d5bcd555466
Revises: 6c8c9701193d
Create Date: 2017-06-13 16:45:13.429905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5bcd555466'
down_revision = '6c8c9701193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('library_prep', sa.Text(), nullable=True),
    sa.Column('automated_library_prep', sa.Text(), nullable=True),
    sa.Column('sample_amount', sa.Text(), nullable=True),
    sa.Column('sequencing_depth', sa.Text(), nullable=True),
    sa.Column('misc', sa.Text(), nullable=True),
    sa.Column('delivery', sa.Text(), nullable=True),
    sa.Column('is_accredited', sa.Boolean(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_unique_constraint('_document_version_uc', 'admin_method', ['document', 'document_version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_document_version_uc', 'admin_method', type_='unique')
    op.drop_table('admin_application')
    # ### end Alembic commands ###
