"""Add data handling column to Customer table

Revision ID: 6a2084ae82c8
Revises: ffb9f8ab8e62
Create Date: 2023-07-04 15:05:25.049373

"""
import sqlalchemy as sa
from alembic import op
from cg.store.models import DataHandlingProtocol

# revision identifiers, used by Alembic.
revision = "6a2084ae82c8"
down_revision = "ffb9f8ab8e62"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        table_name="customer", column=sa.column("data_handling_protocol", DataHandlingProtocol)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name="customer", column_name="data_handling_protocol")
    # ### end Alembic commands ###
