"""Add foreign keys to SampleLaneSequencingMetrics

Revision ID: 9d1483e638af
Revises: f5e0db62a5a7
Create Date: 2023-06-01 13:40:25.835471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d1483e638af'
down_revision = 'f5e0db62a5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_cell_name', sa.String(length=128), nullable=False),
    sa.Column('sample_internal_id', sa.String(length=128), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('yield_in_megabases', sa.Integer(), nullable=True),
    sa.Column('read_counts', sa.Integer(), nullable=True),
    sa.Column('passed_filter_percent', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('raw_clusters_per_lane_percent', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('perfect_index_reads_percent', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('bases_with_q30_percent', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('lanes_mean_quality_score', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sample_lane_sequencing_metrics')
    op.alter_column('analysis', 'family_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('application', 'prep_category',
               existing_type=mysql.ENUM('cov', 'mic', 'rml', 'tgs', 'wes', 'wgs', 'wts'),
               nullable=False)
    op.alter_column('application', 'min_sequencing_depth',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('family', 'priority',
               existing_type=mysql.ENUM('research', 'standard', 'priority', 'express', 'clinical_trials'),
               nullable=False)
    op.alter_column('invoice', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('invoice', 'comment',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_index('customer_invoice_pk', table_name='invoice')
    op.create_foreign_key(None, 'invoice', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'pool', 'invoice', ['invoice_id'], ['id'])
    op.alter_column('sample', 'priority',
               existing_type=mysql.ENUM('research', 'standard', 'priority', 'express', 'clinical_trials'),
               nullable=False)
    op.create_foreign_key(None, 'sample', 'invoice', ['invoice_id'], ['id'])
    op.drop_column('sample', 'beaconized_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('beaconized_at', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.alter_column('sample', 'priority',
               existing_type=mysql.ENUM('research', 'standard', 'priority', 'express', 'clinical_trials'),
               nullable=True)
    op.drop_constraint(None, 'pool', type_='foreignkey')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_index('customer_invoice_pk', 'invoice', ['customer_id'], unique=False)
    op.alter_column('invoice', 'comment',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('invoice', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('family', 'priority',
               existing_type=mysql.ENUM('research', 'standard', 'priority', 'express', 'clinical_trials'),
               nullable=True)
    op.alter_column('application', 'min_sequencing_depth',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('application', 'prep_category',
               existing_type=mysql.ENUM('cov', 'mic', 'rml', 'tgs', 'wes', 'wgs', 'wts'),
               nullable=True)
    op.alter_column('analysis', 'family_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('sample_lane_sequencing_metrics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flow_cell_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('flow_cell_lane_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_internal_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('sample_total_reads_in_lane', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_base_fraction_passing_q30', mysql.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('sample_base_mean_quality_score', mysql.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('sequencing_statistics')
    # ### end Alembic commands ###
