"""add additional status check fields

Revision ID: c7e06157fd9a
Revises: 6606536bbf3c
Create Date: 2017-06-12 17:15:14.646465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e06157fd9a'
down_revision = '6606536bbf3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.add_column('sample', sa.Column('is_external', sa.Boolean(), nullable=True))
    op.add_column('sample', sa.Column('sequenced_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('sample', 'sequenced_at')
    op.drop_column('sample', 'is_external')
    op.drop_column('analysis', 'is_primary')
    # ### end Alembic commands ###
