# 1. submit the samples in an order to the API (authorize as "robin.andeer@scilifelab.se")
curl -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImIzMDY0NjhlYmI3MDFmMzA2OWEyYzA0MTBiNmIxMzdmMjU2Yzg2NDgifQ.eyJhenAiOiI1Nzc0NTA2MDM3ODYtYnJhYjFqZ2sxMGphcGk4c2x0NzlocWs5MnVlM21ocW8uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1Nzc0NTA2MDM3ODYtYnJhYjFqZ2sxMGphcGk4c2x0NzlocWs5MnVlM21ocW8uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDc2NDkzNDA1ODY5MTgyNDk1MzAiLCJoZCI6InNjaWxpZmVsYWIuc2UiLCJlbWFpbCI6InJvYmluLmFuZGVlckBzY2lsaWZlbGFiLnNlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJZOGJDMnE4T2syMGNhUUZweHdKQWhBIiwiaXNzIjoiYWNjb3VudHMuZ29vZ2xlLmNvbSIsImlhdCI6MTUwMDM2MzE2NywiZXhwIjoxNTAwMzY2NzY3LCJuYW1lIjoiUm9iaW4gQW5kZWVyIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS8tM0dPNzBXUUxaRUEvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQXMvTmRIdHhCVHdtbjAvczk2LWMvcGhvdG8uanBnIiwiZ2l2ZW5fbmFtZSI6IlJvYmluIiwiZmFtaWx5X25hbWUiOiJBbmRlZXIiLCJsb2NhbGUiOiJlbiJ9.itlVFPrjLgTlJSmElthlwj5FU1mUDfGkL_cxfdyTaI36d40iErD-idziQow51qTlP-wTQBjmkFvDJTVFtgsItV_QdiHvdwOpOGXQdbycSr4NO_WbrBMiU5uC-xDLdX8bMq4JgQCdACjcx6h3xjvB3A3kfIxcD4q-O0QG6VpRH8DX1HgIU1ZCaRd5MMxT4uwv7kYXTRpvbv1cogsLwKqLi1XYHDg26FbDzogj531IJDUAP6vzOqkIjSgmCG4nkXHWz2Myy36NUtOuFPfwIecVb_7rj0IK7ifbrqUU4OJghzCmqrQewDBABlP-Cd0CJMxlABfzJkDb70h3jR0aL286LA" --data @order.json http://localhost:5000/api/v1/order

# copy the "internal_id" of the generated family

# 2. populate data from related flowcells:
for flowcell in H2V7FCCXX H2TF5CCXX H5VL5CCXX H2NN2CCXX; do
    cg transfer flowcell "${flowcell}"
done

# 3. check which families are not ready for sequencing
cg status analysis
