# -*- coding: utf-8 -*-
import os

SECRET_KEY = 'unsafe!!!'
TEMPLATES_AUTO_RELOAD = True
SQLALCHEMY_DATABASE_URI = os.environ['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_POOL_RECYCLE = 7200
SQLALCHEMY_TRACK_MODIFICATIONS = 'FLASK_DEBUG' in os.environ
CG_ENABLE_ADMIN = 'FLASK_DEBUG' in os.environ or os.environ.get('CG_ENABLE_ADMIN')
