"""Taxprofiler related constants."""


from cg.constants.nextflow import NFX_SAMPLE_HEADER, NFX_SAMPLESHEET_READS_HEADERS
from typing import List

TAXPROFILER_RUN_ACCESSION: str = "run_accession"
TAXPROFILER_INSTRUMENT_PLATFORM: str = "instrument_platform"
TAXPROFILER_FASTA_HEADER: str = "fasta"
TAXPROFILER_SAMPLE_SHEET_HEADERS: List[str] = [
    NFX_SAMPLE_HEADER,
    TAXPROFILER_RUN_ACCESSION,
    TAXPROFILER_INSTRUMENT_PLATFORM,
]

TAXPROFILER_SAMPLE_SHEET_HEADERS += NFX_SAMPLESHEET_READS_HEADERS
TAXPROFILER_SAMPLE_SHEET_HEADERS.append(TAXPROFILER_FASTA_HEADER)


class TaxprofilerDefaults:
    "Taxprofiler default parameteres"

    SAVE_PREPROCESSED_READS: bool = True
    PERFORM_SHORTREAD_QC: bool = True
    PERFORM_SHORTREAD_COMPLEXITYFILTER: bool = True
    SAVE_COMPLEXITYFILTERED_READS: bool = True
    PERFORM_SHORTREAD_HOSTREMOVAL: bool = True
    SAVE_HOSTREMOVAL_INDEX: bool = True
    SAVE_HOSTREMOVAL_MAPPED: bool = True
    SAVE_HOSTREMOVAL_UNMAPPED: bool = True
    RUN_KRAKEN2: bool = True
    KRAKEN2_SAVE_READS: bool = True
    KRAKEN2_SAVE_READCLASSIFICATION: bool = True
    RUN_PROFILE_STANDARDISATION: bool = True
    RUN_KRONA: bool = True
