"""Taxprofiler related constants."""


from cg.constants.nextflow import NFX_SAMPLE_HEADER, NFX_SAMPLESHEET_READS_HEADERS

TAXPROFILER_RUN_ACCESSION = "run_accession"
TAXPROFILER_INSTRUMENT_PLATFORM = "instrument_platform"
TAXPROFILER_ACCEPTED_PLATFORMS = ["ILLUMINA", "OXFORD_NANOPORE"]
TAXPROFILER_FASTA_HEADER = "fasta"
TAXPROFILER_SAMPLESHEET_HEADERS = [
    NFX_SAMPLE_HEADER,
    TAXPROFILER_RUN_ACCESSION,
    TAXPROFILER_INSTRUMENT_PLATFORM,
    # NFX_SAMPLESHEET_READS_HEADERS,
    # TAXPROFILER_FASTA_HEADER,
]
TAXPROFILER_SAMPLESHEET_HEADERS.extend(NFX_SAMPLESHEET_READS_HEADERS)
TAXPROFILER_SAMPLESHEET_HEADERS.extend(TAXPROFILER_FASTA_HEADER)


class TaxprofilerDefaults:
    """Taxprofiler default parameters"""

    INSTRUMENT_PLATFORM: str = "ILLUMINA"
