---
database: "mysql+pymysql://USERNAME:PASSWORD@HOST:PORT/DATABASE"
madeline_exe: "/mnt/hds/proj/bioinfo/resources/madeline2"

housekeeper:
  database: "mysql+pymysql://USERNAME:PASSWORD@HOST:PORT/DATABASE"
  root: "./DEVELOP/bundles"

trailblazer:
  database: "mysql+pymysql://USERNAME:PASSWORD@HOST:PORT/DATABASE"
  script: /mnt/hds/proj/bioinfo/SERVER/miniconda/bin/mip.pl
  mip_config: "/mnt/hds/proj/cust000/STAGE/config/mip.v4.yaml"
  root: /mnt/hds/proj/bioinfo/MIP_ANALYSIS/families

lims:
  host: url
  username: username
  password: password

scout:
  database: "mongodb://USERNAME:PASSWORD@HOST:PORT/DATABASE"
  database_name: database

loqusdb:
  database: "mongodb://USERNAME:PASSWORD@HOST:PORT/DATABASE"
  database_name: database

chanjo:
  database: "mysql+pymysql://USERNAME:PASSWORD@HOST:PORT/DATABASE"

genotype:
  database: "mysql+pymysql://USERNAME:PASSWORD@HOST:PORT/DATABASE"
