name: Add new issues to backlogs

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Clinical-Genomics/projects/39
          github-token: ${{ secrets.REPO_AND_PROJECT_PAT }}
          labeled: rare-disease
          
