---

name: Build container of latest release
on:
  release:
    types:
      - created

jobs:
  docker-image-CI:
    name: Docker Image CI
    runs-on: ubuntu-latest
    steps:

      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Build and publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: clinicalgenomics/cg-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ github.event.release.tag_name }}"