name: Build and publish cli image on push

on: [push]

jobs:
  docker-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Extract branch name and remove illegal chars
        id: get_branch_name
        shell: bash
        run: echo "branch=$(tr "/" "-" <<<${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_cli_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile.cli
          push: true
          tags: "clinicalgenomics/cg-cli:${{ env.branch }}"
