name: CG installation on clinical-db

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Check out cg code
    - uses: actions/checkout@v2

    - name: Set up clinical-db Python 3.6
      uses: actions/setup-python@v2
      # (prod170926) [hiseq.clinical@hippocampus ~]$ date
      # Wed May 27 16:44:09 CEST 2020
      # (prod170926) [hiseq.clinical@hippocampus ~]$ python --version
      # Python 3.6.2 :: Continuum Analytics, Inc.
      # (prod170926) [hiseq.clinical@hippocampus ~]$ pip --version
      # pip 9.0.1
      with:
        python-version: 3.6

    - name: Check production dependency graph
      run: |
        python -m pip install --upgrade pip==9.0.1
        pip install .
        pip check

    - name: Check development dependency graph
      run: |
        pip install -r requirements-dev.txt
        pip check
