name: Tests and coveralls

on: ["push", "pull_request"]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Set up python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install CG dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt

    - name: Install coveralls dependencies
      run: |
        pip install pytest-cov
        pip install coveralls

    - name: Test with pytest & Coveralls
      run: |
        pytest --cov=cg/
        coveralls
      env:
        GITHUB: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
