name: CG Linting and Black

on: [pull_request]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:

    # Check out cg code
    - uses: actions/checkout@v2

    # Set up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Lint Dependencies
      run: |
        pip install flake8 black

    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      # Let black change files
      with:
        github_token: ${{ secrets.github_token }}
        auto_fix: true
        # stop the build if there are Python syntax errors or undefined names
        flake8: true
        flake8_args: "cg/ --count --select=E9,F63,F7,F82 --show-source --statistics"