name: Linting code

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Check out cg code
    - uses: actions/checkout@v2

    # Set up python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install lint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install black


    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      # Let linters fix problems if they can
      with:
        github_token: ${{ secrets.github_token }}
        auto_fix: true
        # Enable linters
        black: true
        black_args: "--check -l 100"
        # stop the build if there are Python syntax errors or undefined names
        flake8: true
        flake8_args: "cg/ --count --select=E9,F63,F7,F82 --show-source --statistics"
