name: Ruff

on: [ push, pull_request ]

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.3.0      
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BUMPVERSION_TOKEN }}
          fetch-depth: 0
          persist-credentials: false 
      
      - name: Ruff action
        uses: chartboost/ruff-action@v1
        with:
          args: "check --fix --ignore F401,E501,F811 --line-length 100 --exclude **/alembic"
          version: "0.1.4"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ruff code formatter"
          commit_user_name: clingen-sthlm
          commit_user_email: ${{ secrets.BUMPVERSION_EMAIL }}
          commit_author: ${{ secrets.BUMPVERSION_AUTHOR }}


