name: Ruff

on: [ push, pull_request ]

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3       
      
      - name: Ruff action
        uses: chartboost/ruff-action@v1
        with:
          args: "check --ignore F401,E501 --fix"
          version: "0.1.4"

