name: Unit tests

on:
  pull_request:

jobs:
  tests-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'

      - name: CG Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt

      - name:  Run pytest
        run: |
          pytest --testmon